debug: true

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG

spring:
  application:
    name: sistema_alertas
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

app:
  rabbitmq:
    exchange_name: ${EXCHANGE_NAME:exchange_alertas}
    queue_name: ${QUEUE_NAME:queue_alertas}
    routing_key_name: ${ROUTING_KEY_NAME:routing_key_alertas}
